export interface IBook {
  id: number;
  title: string;
  author: string;
  image: string;
  year: number;
  publisher: string;
  price: number;
  genres: string[];
  language: string;
  bestseller: boolean;
}

const db: IBook[] = [
  {
    id: 0,
    title: 'Northanger Abbey',
    author: 'Austen, Jane',
    language: 'en',
    genres: ['fiction', 'drama'],
    image:
      'https://img4.labirint.ru/rc/751d838a56705900f7226d5d990375dd/363x561q80/books86/858292/cover.jpg?1652804713',
    year: 1814,
    publisher: 'Penguin',
    price: 18.2,
    bestseller: true,
  },
  {
    id: 1,
    title: 'Война и мир (War and peace)',
    author: 'Толстой Л.Н. (Tolstoy, Leo)',
    language: 'ru',
    genres: ['fiction', 'drama', 'historical', 'epic'],
    image:
      'https://img4.labirint.ru/rc/cc019d44bd4afa5deaa59f6d4f1701e9/363x561q80/books66/650484/cover.jpg?1564120687',
    year: 1865,
    publisher: 'Penguin',
    price: 12.7,
    bestseller: false,
  },
  {
    id: 2,
    title: 'Анна Каренина (Anna Karenina)',
    author: 'Толстой Л.Н. (Tolstoy, Leo)',
    language: 'ru',
    genres: ['fiction', 'drama'],
    image: 'https://www.moscowbooks.ru/image/book/714/orig/i714998.jpg?cu=20210303183514',
    year: 1875,
    publisher: 'Penguin',
    price: 13.5,
    bestseller: false,
  },
  {
    id: 3,
    title: 'Mrs. Dalloway',
    author: 'Woolf, Virginia',
    language: 'en',
    genres: ['fiction', 'drama'],
    image:
      'https://img4.labirint.ru/rc/94d3a979bc1f07745ca79f819d948e43/594x918q80/books82/812974/cover.jpg?1625758123',
    year: 1925,
    publisher: 'Harcourt Brace',
    price: 25,
    bestseller: false,
  },
  {
    id: 4,
    title: 'The Hours',
    author: 'Cunningham, Michael',
    language: 'en',
    genres: ['fiction', 'drama'],
    image: 'https://m.media-amazon.com/images/I/51t5Nldq8kL.jpg',
    year: 1999,
    publisher: 'Harcourt Brace',
    price: 12.35,
    bestseller: false,
  },
  {
    id: 5,
    title: 'Huckleberry Finn',
    author: 'Twain, Mark',
    language: 'en',
    genres: ['fiction', 'adventures'],
    image:
      'https://anylang.net/sites/default/files/covers/adventures-huckleberry-finn-tom-sawyers-comrade.jpg',
    year: 1865,
    publisher: 'Penguin',
    price: 5.76,
    bestseller: false,
  },
  {
    id: 6,
    title: 'Bleak House',
    author: 'Dickens, Charles',
    language: 'en',
    genres: ['fiction', 'drama'],
    image: 'https://www.storytel.com/images/e/640x640/0002490017.jpg',
    year: 1870,
    publisher: 'Random House',
    price: 5.75,
    bestseller: false,
  },
  {
    id: 7,
    title: 'The advantures of Tom Sawyer',
    author: 'Twain, Mark',
    language: 'en',
    genres: ['fiction', 'adventures'],
    image: 'https://i.pinimg.com/originals/42/94/be/4294be1a47ba957d10ed7bc0110c695a.jpg',
    year: 1862,
    publisher: 'Random House',
    price: 7.75,
    bestseller: false,
  },
  {
    id: 8,
    title: "A Room of One's Own",
    author: 'Woolf, Virginia',
    language: 'en',
    genres: ['nonfiction', 'essay'],
    image:
      'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/713a6040851507.5a69dee330e11.jpg',
    year: 1922,
    publisher: 'Penguin',
    price: 29,
    bestseller: false,
  },
  {
    id: 9,
    title: "Harry Potter and Philosofer's stone",
    author: 'Rowling, J.K.',
    language: 'en',
    genres: ['fiction', 'adventures', 'fantasy'],
    image:
      'https://images.ctfassets.net/usf1vwtuqyxm/2DCs73x6P8seNobQ9zBSbO/1a5dfd6ed5fc0ed9545370470fc3d74c/English_Harry_Potter_1_Epub_9781781100219.jpg?w=914&q=70&fm=jpg',
    year: 2000,
    publisher: 'Harcourt Brace',
    price: 19.95,
    bestseller: true,
  },
  {
    id: 10,
    title: 'Cien años de soledad (One Hundred Years of Solitude)',
    author: 'Márquez, Gabriel García (Marquez, Gabriel Garcia)',
    language: 'sp',
    genres: ['fiction', 'fantasy', 'epic'],
    image:
      'https://anylang.net/sites/default/files/styles/book_image/public/covers/cien-anos-de-soledad.jpg?itok=1o0-9UqA',
    year: 1967,
    publisher: 'Harper  Perennial',
    price: 14.0,
    bestseller: false,
  },
  {
    id: 11,
    title: 'Hamlet, Prince of Denmark',
    author: 'Shakespeare, William',
    language: 'en',
    genres: ['fiction', 'poetry'],
    image:
      'https://kbimages1-a.akamaihd.net/ff4d293a-bd38-4732-a323-28d700aedbd7/1200/1200/False/the-tragedy-of-hamlet-prince-of-denmark-16.jpg',
    year: 1862,
    publisher: 'Signet  Classics',
    price: 7.95,
    bestseller: true,
  },
  {
    id: 12,
    title: 'Lord of the Rings',
    author: 'Tolkien, J.R.',
    language: 'en',
    genres: ['fiction', 'fantasy', 'epic'],
    image:
      'https://images.squarespace-cdn.com/content/v1/5694e3d62399a32f9426b07d/1528544385448-EV2KPMEDZMYXKWU45OVC/lord_of_the_rings_book.jpg',
    year: 1937,
    publisher: 'Penguin',
    price: 27.45,
    bestseller: true,
  },
  {
    id: 13,
    title: 'The Rise and Reign of the Mammals',
    author: 'Brusatte, Steve',
    language: 'en',
    genres: ['nonfiction'],
    image: 'https://m.media-amazon.com/images/I/51WErrbDtdL.jpg',
    year: 2022,
    publisher: 'Mariner Books',
    price: 24.5,
    bestseller: true,
  },
  {
    id: 14,
    title: 'Queen of Our Times',
    author: 'Hardman, Robert',
    language: 'en',
    genres: ['nonfiction'],
    image: 'https://m.media-amazon.com/images/I/41l4glr6QCL.jpg',
    year: 2022,
    publisher: 'Simon & Schuster',
    price: 21.25,
    bestseller: true,
  },
  {
    id: 15,
    title: 'Le Petit Prince (The Little Prince)',
    author: 'Antoine de Saint-Exupéry',
    language: 'fr',
    genres: ['fiction', 'adventures'],
    image: 'https://images-na.ssl-images-amazon.com/images/I/81G2R0luQJL.jpg',
    year: 1943,
    publisher: 'Reynal & Hitchcock',
    price: 14.36,
    bestseller: true,
  },
  {
    id: 16,
    title: 'Little Women',
    author: 'Alcott, Louisa May',
    language: 'en',
    genres: ['fiction', 'adventures'],
    image: 'https://images-na.ssl-images-amazon.com/images/I/91l1EHFs8dL.jpg',
    year: 1934,
    publisher: 'Roberts Brothers',
    price: 17.0,
    bestseller: false,
  },
  {
    id: 17,
    title: "The Handmaid's Tale",
    author: 'Atwood, Margaret',
    language: 'en',
    genres: ['fiction', 'drama'],
    image: 'https://images-na.ssl-images-amazon.com/images/I/61SpcaD4poL.jpg',
    year: 1985,
    publisher: 'Stewart Houghton Mifflin Harcourt',
    price: 35.87,
    bestseller: true,
  },
  {
    id: 18,
    title: 'The Testaments',
    author: 'Atwood, Margaret',
    language: 'en',
    genres: ['fiction', 'drama'],
    image: 'https://images-na.ssl-images-amazon.com/images/I/71vHjmxxkBL.jpg',
    year: 2019,
    publisher: 'Chatto & Windus',
    price: 38.5,
    bestseller: true,
  },
  {
    id: 19,
    title: 'Harry Potter and the Goblet of Fire',
    author: 'Rowling, J.K.',
    language: 'en',
    genres: ['fiction', 'adventures', 'fantasy'],
    image:
      'https://img3.labirint.ru/rc/ee537d270e21013fda6041e6d8e98861/363x561q80/books27/263507/cover.jpg?1563604304',
    year: 2002,
    publisher: 'Harcourt Brace',
    price: 19.95,
    bestseller: true,
  },
  {
    id: 20,
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'Rowling, J.K.',
    language: 'en',
    genres: ['fiction', 'adventures', 'fantasy'],
    image: 'https://anylang.net/sites/default/files/covers/harry-potter-and-chamber-secrets.jpg',
    year: 2001,
    publisher: 'Harcourt Brace',
    price: 23.69,
    bestseller: false,
  },
  {
    id: 21,
    title: 'Harry Potter and the Deathly Hallows',
    author: 'Rowling, J.K.',
    language: 'en',
    genres: ['fiction', 'adventures', 'fantasy'],
    image: 'https://anylang.net/sites/default/files/covers/harry-potter-and-deathly-hallows.jpg',
    year: 2008,
    publisher: 'Harcourt Brace',
    price: 27.43,
    bestseller: false,
  },
];

export default db;
